### ISSUE TITLE
`tool-version` will most often be "latest" so should not be required

### ISSUE THREAD

**Issue by JLLeitschuh** [ossf/security-insights-spec#22]
If you want a good security scanner, you should probably always be running the latest version. This field should not be required, and probably shouldn't be present at all.

https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/security-insights-schema-1.0.0.yaml#L289-L292

https://github.com/ossf/security-insights-spec/blob/4e783e0397b2c4bbf3a35144e985dde8f8b9f93e/security-insights-schema-1.0.0.yaml#L298-L302

**Comment by eddie-knight** [comment]
You're right that the value will usually be "latest" for security tooling (which is possible due to it being a string value). But the consensus on our community calls is that this provides a low-cost value by encouraging specificity.

After some debate, we've decided to leave version in here for the official `v1.0.0` release that is being cut next week. Please feel free to bring this up again on a community call if you feel an oversight has been made— and thanks for initiating the conversation!
